export const glossary: Record<string, string> = {
  liberty: 'An empty point directly beside a stone or group — its breathing room.',
  liberties: 'Empty points directly beside a stone or group — its breathing room.',
  atari: 'A group with only one liberty left. Capture is threatened on the very next move.',
  group: 'Stones of one color connected along the lines. They live or die as a single unit.',
  prisoner: 'A captured stone. Each prisoner is worth one point at the end of the game.',
  prisoners: 'Captured stones. Each is worth one point at the end of the game.',
  ko: 'A shape where players could recapture each other forever. The rule: no immediate recapture — you must play elsewhere first.',
  eye: 'An empty point completely surrounded by one group. A group with two eyes can never be captured.',
  eyes: 'Empty points completely surrounded by one group. A group with two eyes can never be captured.',
  territory: 'Empty points fenced in entirely by one color. Each counts as a point at the end.',
  'star point': 'One of the marked dots on the board — landmarks that guide opening play.',
  komi: 'Bonus points White receives as compensation for Black moving first.',
  dame: 'Neutral empty points that belong to neither side and score nothing.',
  corner: 'The easiest place to build territory — the board edge fences two sides for free.',
  corners: 'The easiest places to build territory — the board edges fence two sides for free.',
  enclosure: 'A small wall around a corner stone that fences a chunk of territory.',
  invasion: 'A move played inside the opponent\'s fenced area to live small or run out.',
  extension: 'A stone placed along a side, extending from a corner or group toward more territory.',
  influence: 'The power a stone radiates over nearby intersections — not yet secure territory.',
  'false eye': 'An empty point that looks like an eye but leaks diagonally — it does not give life.',
  'capturing race': 'A fight between two groups without two eyes — whoever runs out of liberties first is captured.',
  seki: 'Mutual life — two groups cannot capture each other; shared empty points score for neither side.',
  reduction: 'A light move that presses against enemy territory from the outside without invading.',
  tenuki: 'To play elsewhere, leaving the local fight for bigger gain on the board.',
  'good shape': 'Efficient, connected stone patterns that share liberties and resist cutting.',
  'bad shape': 'Clumped or wasteful patterns that leak liberties and invite attack.',
  'empty triangle': 'Three stones filling three corners of a 2×2 square — heavy and easy to attack.',
  'table shape': 'Two stones side by side on the same line — a basic good shape.',
  'bamboo joint': 'Two stones on adjacent lines, offset by one — connected and light.',
  ladder: 'A forcing chase in a stair-step pattern until the runner hits the edge or a breaker.',
  'ladder breaker': 'A friendly stone on the ladder’s path that lets the runner escape.',
  reading: 'Mentally playing out a sequence before placing a stone — seeing the whole fight ahead.',
  net: 'A loose surrounding shape, often a knight’s move, that traps a running stone.',
  snapback: 'Sacrificing a small capture so the immediate recapture wins a larger group.',
  'throw-in': 'Sacrificing a stone inside an eye so the forced capture shrinks the opponent’s living space.',
  'double atari': 'One move that puts two enemy groups into atari at once — only one can be saved.',
  'life and death': 'Whether a group can live with two eyes or be killed — the heart of Go puzzles.',
  'vital point': 'The single intersection that decides whether a group lives or dies.',
  'L-group': 'Three stones in an L shape in the corner — a classic dead shape when surrounded.',
  running: 'Escaping with weak stones toward open area or friendly support.',
  Running: 'Escaping with weak stones toward open area or friendly support.',
  'bent four': 'Four stones in a bent square in the corner — dead when fully surrounded.',
  'puzzle rhythm': 'The habit of pausing to classify a fight — kill, live, or run — before playing.',
  haengma: 'Stone flow — how groups move across the board; urgent before big.',
  'urgent move': 'A local play that fixes weakness or prevents immediate loss — before big points.',
  'weak group': 'Stones with few eyes, few liberties, or cutting points — vulnerable to attack.',
  'weak groups': 'Stones with few eyes, few liberties, or cutting points — vulnerable to attack.',
  peep: 'A one-point probe that threatens to cut — forcing the opponent to answer.',
  sacrifice: 'Giving up stones deliberately to save a larger group or gain sente.',
  miai: 'Two equivalent points — if you play one, the opponent must answer; either works.',
  thickness: 'Solid, outward-facing stone power that radiates influence without being territory yet.',
  moyo: 'A large framework of potential territory built from influence and open space.',
  overconcentration: 'Playing too many stones in one small area — inefficient and heavy.',
  joseki: 'A standard corner sequence both players accept — a trade of territory and influence.',
  'ko threat': 'A move played elsewhere to force an answer before recapturing the ko stone.',
  sente: 'A move the opponent should answer locally — you keep the initiative.',
  gote: 'A move the opponent can ignore — you played last locally and they choose elsewhere.',
  'double sente': 'A local point both players want to play first — huge endgame value.',
  yose: 'The endgame — filling the last profitable points before scoring.',
  Haengma: 'Stone flow — how groups move across the board; urgent before big.',
  'Weak groups': 'Stones with few eyes, few liberties, or cutting points — vulnerable to attack.',
  Peep: 'A one-point probe that threatens to cut — forcing the opponent to answer.',
  Sacrifice: 'Giving up stones deliberately to save a larger group or gain sente.',
  Miai: 'Two equivalent points — if you play one, the opponent must answer; either works.',
  Thickness: 'Solid, outward-facing stone power that radiates influence without being territory yet.',
  Reduction: 'A light move that presses against enemy territory from the outside without invading.',
  Overconcentration: 'Playing too many stones in one small area — inefficient and heavy.',
  Yose: 'The endgame — filling the last profitable points before scoring.',
  'Double sente': 'A local point both players want to play first — huge endgame value.',
  Dame: 'Neutral empty points that belong to neither side and score nothing.',
  'Urgent move': 'A local play that fixes weakness or prevents immediate loss — before big points.',
  Sente: 'A move the opponent should answer locally — you keep the initiative.',
  Gote: 'A move the opponent can ignore — you played last locally and they choose elsewhere.'
};